- crates/threshold-signature-server/src/user/api.rs
- crates/threshold-signature-server/src/user/tests.rs
The error is not really an error and should just log a warning
> Downgrade `check_in_registration_group` error log to warning

- README.md
Adds a small section callout that points readers to the Support workflow.
> Adds Support section for general help.

- crates/client/src/user.rs
> Fix hardcoded threshold amount

- crates/threshold-signature-server/src/helpers/tests.rs
- crates/threshold-signature-server/src/user/tests.rs
- crates/threshold-signature-server/tests/register_and_sign.rs
- crates/threshold-signature-server/tests/sign_eth_tx.rs
Closes https://github.com/entropyxyz/entropy-core/issues/1069
> Unignore register and sign integration test, and do a non-mock jumpstart

- crates/client/src/client.rs
Related PR: https://github.com/entropyxyz/entropy-network-status-page/pull/21
> Minor fixes to entropy-client needed for updating the status page

- README.md
In response to : https://github.com/entropyxyz/entropy-core/issues/1110
Wanted to offer this PR that makes it easier for others to get started with `entropy-core` :pray: :blue_heart:
> Improve documentation references in `README`

- CHANGELOG.md
- Cargo.lock
- crates/client/Cargo.toml
- crates/client/src/client.rs
- crates/client/src/errors.rs
- crates/client/src/tests.rs
- crates/test-cli/src/lib.rs
Closes https://github.com/entropyxyz/entropy-core/issues/1167
> Add command to get oracle headings

- crates/protocol/src/execute_protocol.rs
Closes https://github.com/entropyxyz/entropy-core/issues/1151
> Use an internal queue for messages with mismatched session id in protocol execution loop

- Cargo.lock
- crates/threshold-signature-server/Cargo.toml
Closes https://github.com/entropyxyz/entropy-core/issues/1182
(I hope)
> Use published version of entropy-programs-runtime v0.11.0

- crates/threshold-signature-server/src/backup_provider/api.rs
- crates/threshold-signature-server/src/backup_provider/errors.rs
- crates/threshold-signature-server/src/helpers/launch.rs
- crates/threshold-signature-server/src/helpers/tests.rs
- crates/threshold-signature-server/src/lib.rs
This is a sub-pr of https://github.com/entropyxyz/entropy-core/pull/1249
> Add an extra TSS state for connected to chain but not funded / fully ready

- crates/shared/src/types.rs
- crates/threshold-signature-server/src/helpers/user.rs
- crates/threshold-signature-server/src/user/api.rs
See https://github.com/entropyxyz/entropy-core/pull/1266#discussion_r1933391577
> HashingAlgorithm enum should use u32 not usize

- crates/protocol/src/execute_protocol.rs
This is not a functional change, just a tiny refactor.
I wanted to check that it is possible to pass a mutable reference to the channels used in the `entropy-protocol` protocol execution loop rather than having the function consume them and then return them again.
This is to match the API of the proposed changes in https://github.com/entropyxyz/manul/pull/91
> Protocol execution loop takes a mutable reference to channels

- crates/threshold-signature-server/src/backup_provider/api.rs
- crates/threshold-signature-server/src/helpers/app_state.rs
- crates/threshold-signature-server/src/helpers/launch.rs
- crates/threshold-signature-server/src/helpers/mod.rs
- crates/threshold-signature-server/src/helpers/signing.rs
- crates/threshold-signature-server/src/helpers/tests.rs
- crates/threshold-signature-server/src/lib.rs
- crates/threshold-signature-server/src/node_info/api.rs
- crates/threshold-signature-server/src/signing_client/api.rs
- crates/threshold-signature-server/src/signing_client/protocol_transport.rs
- crates/threshold-signature-server/src/unsafe/api.rs
- crates/threshold-signature-server/src/user/api.rs
- crates/threshold-signature-server/src/user/tests.rs
- crates/threshold-signature-server/src/validator/api.rs
> Create cache in app state

- Cargo.lock
- crates/threshold-signature-server/src/attestation/api.rs
- crates/threshold-signature-server/src/attestation/errors.rs
- crates/threshold-signature-server/src/attestation/tests.rs
- crates/threshold-signature-server/src/helpers/app_state.rs
- crates/threshold-signature-server/src/helpers/launch.rs
- crates/threshold-signature-server/src/helpers/tests.rs
- crates/threshold-signature-server/src/main.rs
- crates/threshold-signature-server/src/signing_client/api.rs
- crates/threshold-signature-server/src/signing_client/tests.rs
- crates/threshold-signature-server/src/unsafe/api.rs
- crates/threshold-signature-server/src/unsafe/tests.rs
- crates/threshold-signature-server/src/user/api.rs
- crates/threshold-signature-server/src/user/tests.rs
- crates/threshold-signature-server/src/validator/api.rs
- crates/threshold-signature-server/src/validator/tests.rs
> Add block numbers to cache

- pallets/programs/src/lib.rs
- pallets/registry/src/lib.rs
- pallets/staking/src/lib.rs
Closes #1314 
Seems like upstream with ```DispatchResultWithPostInfo``` clippy check removed
> Useless conversion clippy error

- crates/threshold-signature-server/src/attestation/errors.rs
- crates/threshold-signature-server/src/backup_provider/errors.rs
- crates/threshold-signature-server/src/helpers/app_state.rs
- crates/threshold-signature-server/src/signing_client/errors.rs
- crates/threshold-signature-server/src/user/errors.rs
- crates/threshold-signature-server/src/validator/errors.rs
> Add app state error enum

- .github/workflows/build-and-run-node-test.yaml
> Add 90 minute timeout for node-test workfow

- .github/workflows/build-and-run-node-test.yaml
Closes https://github.com/entropyxyz/entropy-core/issues/1332
Probably there is a less verbose way to do this.
> Always run node-test workflow but only actually run the tests if rust code has been modified

- crates/threshold-signature-server/src/attestation/api.rs
- crates/threshold-signature-server/src/attestation/tests.rs
Fixes the attestation validate function's race condition. Not sure if this is actually needed or we should remove this attest code
> Fix attest validate function

- crates/shared/src/types.rs
- crates/threshold-signature-server/src/attestation/api.rs
- crates/threshold-signature-server/src/attestation/errors.rs
- crates/threshold-signature-server/src/attestation/tests.rs
- crates/threshold-signature-server/src/lib.rs
- pallets/propagation/src/lib.rs
Closes https://github.com/entropyxyz/entropy-core/issues/1351
> Remove dead code releating to attestation

- crates/threshold-signature-server/src/attestation/api.rs
- crates/threshold-signature-server/src/helpers/app_state.rs
- crates/threshold-signature-server/src/signing_client/api.rs
- crates/threshold-signature-server/src/signing_client/tests.rs
- crates/threshold-signature-server/src/user/api.rs
- crates/threshold-signature-server/src/validator/api.rs
> Read and write `BlockNumbers` holding a single lock

- crates/client/src/tests.rs
- crates/testing-utils/src/helpers.rs
- crates/threshold-signature-server/src/backup_provider/tests.rs
- crates/threshold-signature-server/src/user/tests.rs
- crates/threshold-signature-server/tests/jumpstart_register_sign.rs
- crates/threshold-signature-server/tests/sign_eth_tx.rs
> Create return type for spawn tss nodes

- CHANGELOG.md
- crates/client/src/client.rs
- crates/protocol/tests/helpers/mod.rs
- crates/threshold-signature-server/src/attestation/tests.rs
- crates/threshold-signature-server/src/backup_provider/api.rs
- crates/threshold-signature-server/src/lib.rs
- crates/threshold-signature-server/src/node_info/tests.rs
- crates/threshold-signature-server/src/signing_client/protocol_transport.rs
- crates/threshold-signature-server/src/signing_client/tests.rs
- crates/threshold-signature-server/src/user/api.rs
- crates/threshold-signature-server/src/user/tests.rs
- crates/threshold-signature-server/src/validator/tests.rs
- node/cli/src/service.rs
- pallets/propagation/src/lib.rs
- pallets/propagation/src/tests.rs
Closes #181 
Will wait to merge after #1380
> Add v1 to all endpoints

- runtime/src/lib.rs
> Fix non local definitions warning

- CHANGELOG.md
- pallets/propagation/src/lib.rs
Closes #1323 
Will update issue with a point of how it was done (instead of here to keep a longer history of the action)
> Remove deadlines in OCW

- CHANGELOG.md
- node/cli/Chainspec-README.md
- node/cli/src/chain_spec/testnet.rs
- node/cli/test-chainspec-inputs/example-chainspec-inputs.json
Closes https://github.com/entropyxyz/entropy-core/issues/1448
TODO:
> Add initial authorities to testnet chainspec inputs

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
> Add palled_delegated_staking

- .github/workflows/build-and-run-node-test.yaml
- crates/threshold-signature-server/src/user/tests.rs
Fixes the first issue but there is a delicate race condition of a block being create, and unfortunately in this test we do need block creation so I added the if statment to capture this problem
> Fix ```Validate_jumpstart_fail```

- crates/client/Cargo.toml
- crates/client/src/errors.rs
- crates/client/src/forest.rs
> Generalize Tree State
