crates/test-cli/src/main.rs

While using the test cli it expects a name like alice one etc, however this makes it hard to input mnemonics which we will need for testnet as those named accounts no longer and should not have funds

Change to mnemonic entry for cli

---

crates/testing-utils/Cargo.toml
crates/threshold-signature-server/Cargo.toml
deny.toml

I ran into https://github.com/rust-lang/cargo/issues/4242 while trying to publish the
`entropy-tss` crate due to a cyclical dependency with the `entropy-testing-utils` crate.
One solution here is to simply remove the specified version number from the
`dev-dependency` causing issues.
I've also changed the `publish` flag for `entropy-testing-utils` to allow it to be
published.

Fixes for publishing `entropy-tss` and `entropy-testing-utils`

---

CHANGELOG.md
Cargo.lock
crates/client/Cargo.toml
crates/kvdb/Cargo.toml
crates/protocol/Cargo.toml
crates/shared/Cargo.toml
crates/test-cli/Cargo.toml
crates/testing-utils/Cargo.toml
crates/threshold-signature-server/Cargo.toml
node/cli/Cargo.toml
pallets/parameters/Cargo.toml
pallets/programs/Cargo.toml
pallets/propagation/Cargo.toml
pallets/registry/Cargo.toml
pallets/slashing/Cargo.toml
pallets/staking/Cargo.toml
pallets/transaction-pause/Cargo.toml
runtime/Cargo.toml

This PR is a follow up to https://github.com/entropyxyz/entropy-core/pull/836.
It's been a few days since its release and I think the DevOps and SDK teams have had time
to catch up with changes and check for general correctness.
Included in this release on top of the `rc.1` changes are:
- Small version bumps for some dependencies
- Some versioning fixes which were needed for publishing to crates.io
- One change to account inputs for the `entropy-test-cli` (#838)
The only critical thing we really need to include are the publishing changes, but I
figured that including the other changes wasn't really that risky/wouldn't change
anything functional about the release. If anybody disagrees I can create a different
release branch with just the publishing change PR cherry-picked in.

Release `v0.1.0`

---

RELEASE_CHECKLIST.md

Because needing to make fixes when a release either does not build or does not immediately seem to work, update the release checklist to propose having the release candidate number in the tag name.
We should probably also propose this on the wiki page we link to in the release checklist: https://github.com/entropyxyz/meta/wiki/Release-management

Update release checklist to reflect current process

---

crates/threshold-signature-server/src/helpers/launch.rs
crates/threshold-signature-server/src/main.rs
crates/threshold-signature-server/src/validator/api.rs
crates/threshold-signature-server/src/validator/tests.rs

There's been some confusion around the usage of `--no-sync`. This PR adds some
documentation around when it should and shouldn't be used.
Admittedly, the crux of the issue stems from having TSS IP addresses on-chain without any
way to determine if they're properly synced or not. If we knew this status we could have
the TSS itself determine whether or not to accept a peers key-shares.
I've also done one little tidy of the logic check around syncing 🧹
cc @vitropy @mixmix

Improve `--no-sync` docs and tiny sync check

---

Cargo.lock
crates/client/Cargo.toml
crates/client/src/errors.rs
crates/kvdb/Cargo.toml
crates/kvdb/src/kv_manager/value.rs
crates/protocol/Cargo.toml
crates/protocol/src/errors.rs
crates/protocol/src/execute_protocol.rs
crates/protocol/src/lib.rs
crates/protocol/src/protocol_message.rs
crates/protocol/src/protocol_transport/mod.rs
crates/protocol/tests/helpers/mod.rs
crates/protocol/tests/protocol.rs
crates/shared/src/constants.rs
crates/testing-utils/Cargo.toml
crates/testing-utils/src/tss_server_process.rs
crates/threshold-signature-server/Cargo.toml
crates/threshold-signature-server/src/helpers/signing.rs
crates/threshold-signature-server/src/helpers/tests.rs
crates/threshold-signature-server/src/helpers/user.rs
crates/threshold-signature-server/src/signing_client/api.rs
crates/threshold-signature-server/src/signing_client/protocol_execution/context.rs
crates/threshold-signature-server/src/signing_client/protocol_execution/mod.rs
crates/threshold-signature-server/src/signing_client/tests.rs
crates/threshold-signature-server/src/user/api.rs
crates/threshold-signature-server/src/user/tests.rs
node/cli/src/chain_spec/integration_tests.rs

This updates synedrion with the latest changes - moving towards adding threshold signing but not actually functionally changing things for now.
Stored keyshares in the kvdb are now no longer `KeyShare<KeyParams>` but `(ThresholdKeyShare<KeyParams, PartyId>, AuxInfo<KeyParams, PartyId>)`. `entropy-protcol` has a type alias for this, `entropy_protocol::KeyShareWithAuxData`.  But we could also make a struct with some nice helpers.
The proactive refresh protocol is still called proactive refresh in our code, but under the hood it is now a key reshare with the same participants as before. This is to distinguish it from a key reshare which changes participants, which we may want to add at some point.

Bump synedrion to unreleased git version ahead of adding t-of-n in Migrate-To-Threshold branch

---

CHANGELOG.md
crates/threshold-signature-server/src/helpers/launch.rs
crates/threshold-signature-server/src/main.rs

This is a follow up to #853, in which the `--mnemonic` flag was introduced.
Now we add support for passing a mnemonic via a file with the `--mnemonic-file` flag, or
through an environment variable, `THRESHOLD_SERVER_MNEMONIC`.
The behaviour around overwriting existing mnemonics if any of these are supplied remains
the same.
Closes #862.

Add support for `--mnemonic-file` and `THRESHOLD_SERVER_MNEMONIC`

---

CHANGELOG.md
crates/client/src/client.rs
crates/client/src/user.rs
crates/shared/src/types.rs
crates/threshold-signature-server/src/user/api.rs
crates/threshold-signature-server/src/user/tests.rs
crates/threshold-signature-server/src/validation/errors.rs
crates/threshold-signature-server/src/validation/mod.rs
crates/threshold-signature-server/src/validator/api.rs
crates/threshold-signature-server/src/validator/tests.rs
crates/threshold-signature-server/tests/protocol_wasm.rs

Replace timestamp with block number

---

crates/test-cli/README.md

I tried out the example commands in the test-cli readme and one of the register ones didn't work

Fix example in `test-cli` readme

---

crates/test-cli/README.md

Tell the reader to install OpenSSL and PKG Config, along with Debian/Ubuntu and Arch pasteables.
Closes https://github.com/entropyxyz/entropy-core/issues/855

Adds deps to Test CLI install instructions.

---

Cargo.lock
crates/protocol/Cargo.toml
crates/protocol/src/errors.rs
crates/protocol/src/execute_protocol.rs
crates/protocol/src/protocol_message.rs
crates/protocol/src/protocol_transport/broadcaster.rs
crates/protocol/tests/helpers/mod.rs
crates/protocol/tests/protocol.rs
crates/threshold-signature-server/src/helpers/tests.rs
crates/threshold-signature-server/src/helpers/user.rs
crates/threshold-signature-server/src/signing_client/protocol_execution/mod.rs

This updates the DKG protocol to internally use the 3 protocols needed for setting up threshold keyshares (key init, reshare, and aux gen), and adds an integration test for `entropy-protocol` demonstrating t of n signing.
It is not yet possible to test this with `entropy-tss` because of not having enough nodes in our test setup, so currently `entropy-tss` always uses a threshold of n.
During the DKG protocols, we need to send the verifying key to the parties who were not present in the Key Init session. To be able to do this, the payload of a `ProtocolMessage` is now an enum which may either be a synedrion protocol message, or a verifying key.  This is a bit ugly - it might be nicer if this passing of the verifying key could be represented as a synedrion `CombinedMessage`.

t of n key generation and signing at the `entropy-protocol` level 

---

CHANGELOG.md
crates/shared/src/types.rs
crates/threshold-signature-server/src/helpers/user.rs
crates/threshold-signature-server/src/node_info/tests.rs
crates/threshold-signature-server/src/user/errors.rs

Blake2 is used to hash ECDSA signer payloads on substrate / polkadot. So i think it makes sense to have it as one of our built in hash functions. This PR does that.
Ive also marked the `HashingAlgorithm` enum as `non_exhaustive`.  This means we handle the case that it was some unknown variant and return a user error if it was.  The idea is to future proof - meaning we can add extra variants without breaking validators who didn't yet update their software.  There are probably arguments against doing this, so im willing to take it out if people think its a bad idea.

Add blake2 as built in hash function and make `HashingAlgorithm` non-exhaustive

---

README.md
docker-compose-common.yaml
docker-compose.yaml

Issue #778 describes "fragmented" docs, but the documentation that was linked to does not actually describe in much detail how to run a development network. Rather, it describes the technical architecture of a development network's start up sequence, and at some length. For example, it included message sequence diagrams that are a bit outdated today.
A more immediately useful reference for a user who attempts to spin up an Entropy Network using the local Docker Compose configuration provided here may be to point them directly at the new Entropy CLI tool, and to reference the public-facing documentation that is current. Moreover, the private repository linked is intended for internal Entropy uses only. While that might have been sensible to link to in the past, it no longer is.
While …

Replace link to private repo with succinct explanation.

---

CHANGELOG.md
crates/client/src/user.rs
crates/threshold-signature-server/src/lib.rs
crates/threshold-signature-server/src/node_info/api.rs
crates/threshold-signature-server/src/node_info/tests.rs
crates/threshold-signature-server/src/user/tests.rs

Closes #890 
Adds a sort function to help with a more deterministic subgroup get across different libraries and languages, as well adds a helper endpoint to get the subgroup with hash

Add sort to subgroup signer selection

---

node/cli/src/service.rs

This was introduced in both #835 and #883. Having this duplicated causes the
Clippy linting step to fail.

Remove duplicate `dead_code` lint

---

crates/kvdb/src/lib.rs
crates/threshold-signature-server/src/health/tests.rs
crates/threshold-signature-server/src/node_info/tests.rs
crates/threshold-signature-server/src/validator/tests.rs

Turns out there were clean_test() in functions that did not spin up a kvdb causing sometimes (if the kvdb was not cleared in the previous test) a panic and failing test issue. The clean_test() function now checks before trying to delete the file and has been removed when not needed

Fix failing kvdb tests

---

scripts/benchmarks.sh

These broke after the ED changes from #901. I haven't been able to solve this in a satisfactory way,
so in order to keep the `v0.2.0` release pipeline moving I suggest we ignore this for now and
investigate later.
See #914 for more details.

Exclude nomination pool benches

---

crates/threshold-signature-server/src/helpers/launch.rs

In #902 a couple more TSS development accounts were added. However, they were not checked when
running through the password prompt code, meaning that a password had to be added when using these
accounts.
For running some of our development flows (e.g `docker compose up`) this isn't ideal.
I've made a quick fix for this in the interest of getting the `v0.2.0` release out today, but the
proper solution here would be to use something like Clap's [`ValueEnum`](https://docs.rs/clap/latest/clap/trait.ValueEnum.html)
and ensure that we check all variants every time they're used.

Skip password prompt for TSS development accounts

---

CHANGELOG.md
Cargo.lock
crates/client/Cargo.toml
crates/kvdb/Cargo.toml
crates/protocol/Cargo.toml
crates/shared/Cargo.toml
crates/test-cli/Cargo.toml
crates/testing-utils/Cargo.toml
crates/threshold-signature-server/Cargo.toml
node/cli/Cargo.toml
pallets/parameters/Cargo.toml
pallets/programs/Cargo.toml
pallets/propagation/Cargo.toml
pallets/registry/Cargo.toml
pallets/slashing/Cargo.toml
pallets/staking/Cargo.toml
pallets/transaction-pause/Cargo.toml
runtime/Cargo.toml

Follow up to #910.
Only changes since then are some dependency bumps from Dependabot and #929.
:shipit:

Release `v0.2.0`

---

Cargo.lock
crates/threshold-signature-server/Cargo.toml
crates/threshold-signature-server/src/helpers/launch.rs
crates/threshold-signature-server/src/main.rs
crates/threshold-signature-server/src/user/tests.rs

Right now the TSS panics and crashes if it's not able to establish a connection with a
Substrate node or if the TSS account doesn't meet a minimum balance.
This PR makes it so that the TSS server retries establishing a connection for ~15 mins
before calling it quits. It also doesn't crash if the TSS account doesn't have a minimum
balance, instead it prints a warning and continues.

Make TSS startup checks more forgiving

---

.dockerignore
docker-compose.yaml
node/cli/src/chain_spec/dev.rs
node/cli/src/command.rs

This adds a third node to our `devnet-local` chainspec and adds that to our Docker
Compose setup.
While the containers spin up correctly, I've ran into some issues around TSS accounts not
being funded properly and with signing not working on the test CLI. Since these issues
aren't exactly related to the Docker stuff I'm gonna dig into those in some different
PRs.
Closes #892.

Add three-node `devnet-local` configuration

---

Cargo.lock
crates/client/Cargo.toml
crates/kvdb/Cargo.toml
crates/protocol/Cargo.toml
crates/protocol/src/errors.rs
crates/protocol/src/execute_protocol.rs
crates/protocol/src/protocol_message.rs
crates/protocol/tests/protocol.rs
crates/testing-utils/Cargo.toml
crates/testing-utils/src/create_test_keyshares.rs
crates/threshold-signature-server/Cargo.toml
crates/threshold-signature-server/src/signing_client/protocol_execution/mod.rs
scripts/create-test-keyshares/Cargo.toml

The latest `HEAD` of Synedrion includes child key derivation functionality that I need
for the new registration flow, so I had to update the dependency.
Two things to note:
- I'm using my own branch of Synedrion until
https://github.com/entropyxyz/synedrion/pull/133 gets merged since that adds some
`serde` support that I need
- There are one or two `TODO`s in places where I want to double check that functionality
remained the same, but I'll do that tomorrow. I'd still consider the PR as a whole
ready for review

Bump Synedrion to latest `master`

---

pallets/staking/src/mock.rs
pallets/staking/src/tests.rs

There were some warnings around unused `Result`s and functions, so I've fixed those. I also did a
tiny cleanup with the types.

Fix warnings when running Staking tests

---

README.md
crates/test-cli/README.md

Add instructions for adding Charlie Docker address to `/etc/hosts`

---

crates/protocol/src/execute_protocol.rs
crates/protocol/src/protocol_message.rs

Merging https://github.com/entropyxyz/entropy-core/pull/946 means we can now get the session Id from synedrion protocol messages and don't need to store it a second time in `ProtocolMessage`.

Remove session hash from protocol message 

---

crates/shared/src/constants.rs
crates/threshold-signature-server/src/helpers/launch.rs
crates/threshold-signature-server/src/user/tests.rs
crates/threshold-signature-server/src/validator/api.rs
crates/threshold-signature-server/src/validator/errors.rs
crates/threshold-signature-server/src/validator/tests.rs
pallets/staking/src/lib.rs

validate new reshare

---

Cargo.lock
crates/client/Cargo.toml
crates/kvdb/Cargo.toml
crates/protocol/Cargo.toml
crates/protocol/src/execute_protocol.rs
crates/testing-utils/Cargo.toml
crates/testing-utils/src/create_test_keyshares.rs
crates/threshold-signature-server/Cargo.toml
scripts/create-test-keyshares/Cargo.toml

I didn't want to bump it in #955 since it could've introduced a lot of noise. Now that I need some
of new child key derivation APIs in the TSS it makes sense to update it elsewhere.

Bump Synedrion to latest `master` in TSS

---

CHANGELOG.md
node/cli/src/chain_spec/mod.rs

Keys were generated incorrectly with subkey when we needed to use hpke

Fix TSS `AccountId` keys in chainspec

---

crates/threshold-signature-server/src/helpers/substrate.rs
crates/threshold-signature-server/src/user/mod.rs
crates/threshold-signature-server/src/user/tests.rs
crates/threshold-signature-server/src/validator/tests.rs
pallets/registry/src/lib.rs

While working on the signing flow I realized that there wasn't a test checking the new
registration flow on the TSS side (which is a pre-requisite to doing signing).
I've added a mostly happy-path test for registration. I don't really want to get bogged
down in checking all the failure scenarios until after the signing flow is done.

Add new registration flow test to TSS side

---

CHANGELOG.md
crates/threshold-signature-server/src/validator/api.rs
crates/threshold-signature-server/src/validator/tests.rs

Delete old keyshare if not in next_signers

---

CHANGELOG.md
crates/protocol/src/execute_protocol.rs
crates/protocol/tests/helpers/mod.rs
crates/threshold-signature-server/src/signing_client/api.rs
crates/threshold-signature-server/src/user/tests.rs
crates/threshold-signature-server/src/validator/api.rs

Related #941 
Refactors reshare to share code between proactive refresh and reshare, mainly by pulling key reshare inputs out to a hire level and passed through

Refactor reshare

---

CHANGELOG.md
crates/client/Cargo.toml
crates/client/src/client.rs
crates/client/src/errors.rs
crates/test-cli/src/lib.rs

This PR adds a way to trigger a network jumpstart from the test CLI. This is useful for ensuring the
network is in the correct state before registering using the new registration flow.

Add `network-jumpstart` command to `entropy-test-cli`

---

pallets/attestation/Cargo.toml
pallets/attestation/src/lib.rs

Just a few things I saw, feel free to close if not the vibe

Clean attestation pallet

---

crates/testing-utils/src/lib.rs
crates/threshold-signature-server/src/helpers/tests.rs
crates/threshold-signature-server/src/user/tests.rs
crates/threshold-signature-server/tests/register_and_sign.rs

@HCastano you don't need to merge this, i just wanted to see it passing.
I really wanted to make this an integration test, but it didn't work out.  The cool thing about the new registration flow is that we can test it in integration because it doesn't rely on there being multiple chain nodes.
But not quite. We have the pre-existing parent keyshares - but we don't have a way to get the chain to a state where jumpstart is completed. The staking extension pallet's genesis config would need to let us put the chain into a jump start completed state.  Something for another PR.

Add test showing register and sign with test client

---

pallets/parameters/src/benchmarking.rs

In https://github.com/entropyxyz/entropy-core/pull/978/ a couple of extra checks were added to
ensure that parameters related to signing could only change so quickly. This ended up breaking one
of the benchmarks since the benchmark setup used a difference that was larger than the allowed
amount.
I've fixed that by reading the current values from storage (set at Genesis) and updating those by
the allowed amount.
Maybe worth revisiting https://github.com/entropyxyz/entropy-core/pull/916...

Fix `change_signers_info` benchmark

---

node/cli/src/chain_spec/dev.rs
node/cli/src/chain_spec/integration_tests.rs

CI on master is failing because of missing imports of `BoundedVec` - quite possibly my fault, as these were introduced in https://github.com/entropyxyz/entropy-core/pull/1024 - but i dont exactly know what happened.

Add missing BoundedVec imports

---

Cargo.lock
crates/threshold-signature-server/Cargo.toml
pallets/attestation/Cargo.toml

This explicitly specifies which commit of TDX quote is used, and uses the latest commit which has changes for parsing the certification data.  Once the TDX attestation feature is done (and before the next release), this crate will be published and we can use a release version number.
I closed https://github.com/entropyxyz/entropy-core/pull/1044 in favor of this.

Bump tdx-quote - and specify a version

---

crates/client/src/tests.rs
crates/shared/src/constants.rs
crates/testing-utils/src/helpers.rs
crates/testing-utils/src/node_proc.rs
crates/testing-utils/src/substrate_context.rs
crates/threshold-signature-server/src/signing_client/tests.rs
crates/threshold-signature-server/src/user/tests.rs
crates/threshold-signature-server/src/validator/tests.rs
crates/threshold-signature-server/tests/register_and_sign.rs
crates/threshold-signature-server/tests/sign_eth_tx.rs

Reduces testing time significantly as blocks all come in, in 6 seconds instead of being skipped. 
Can push this farther by adding this to the other substrate spin up methods (there are few and it may not have as added an effect)

Run multiple test validator

---

crates/threshold-signature-server/src/helpers/tests.rs
crates/threshold-signature-server/src/validator/tests.rs

Fixes master build by not querying potentially missed event then repinging until the event block had been pruned, this instead just goes to non pruning state of the chain

Fix master build

---

crates/test-cli/src/lib.rs

I wanted to try out our latest changes with docker-compose, and i ran into some problems.
- Program hashes were being interpreted as program version numbers, making it impossible to register without giving a version number:
```
/r/s/e/e/c/test-cli (master●●)$ cargo run --release -- register -m //Alice 3289435006003c3c83da5582d779d810c343f177fb1fecddbaca5d326ef9d9b3
Finished `release` profile [optimized] target(s) in 0.55s
Running `/home/turnip/radish/src/entropy/entropy-core/target/release/entropy-test-cli register -m //Alice 3289435006003c3c83da5582d779d810c343f177fb1fecddbaca5d326ef9d9b3`
error: invalid value '3289435006003c3c83da5582d779d810c343f177fb1fecddbaca5d326ef9d9b3' for '[PROGRAM_VERSION_NUMBERS]...': invalid digit found in string 
```
- When storing a program, you cannot find …

Small fixes to `test-cli`

---

crates/client/src/client.rs
crates/client/src/errors.rs

Ahead of us making a release i wanted to try out our current setup with docker-compose. I should have known it was not going to work with the relaying because we have 3 nodes and all are signers - so there is no-one to be a relayer for our signature requests.
This is what happens when we try to sign:
```
~/r/s/e/e/c/test-cli (master●●)[130] $ cargo run --release -- sign -m //Alice 0380b55a941d514baf9e5c4b96239cda40c1854f83919262029bdfec340aed4c13 'heysdlafkjsdlfkj'
Finished `release` profile [optimized] target(s) in 0.51s
Running `/home/turnip/radish/src/entropy/entropy-core/target/release/entropy-test-cli sign -m //Alice 0380b55a941d514baf9e5c4b96239cda40c1854f83919262029bdfec340aed4c13 heysdlafkjsdlfkj`
User account for current call: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY …
```

Avoid panic by checking that we have a non-signing validator before selecting one

---

crates/threshold-signature-server/src/user/tests.rs

Fix faucet test

---

crates/threshold-signature-server/src/signing_client/protocol_execution/mod.rs
crates/threshold-signature-server/src/user/api.rs
crates/threshold-signature-server/src/user/errors.rs
crates/threshold-signature-server/src/user/mod.rs
crates/threshold-signature-server/src/user/tests.rs

Remove bad clippy ignores

---

Cargo.lock
crates/client/Cargo.toml
crates/kvdb/Cargo.toml
crates/protocol/Cargo.toml
crates/testing-utils/Cargo.toml
crates/threshold-signature-server/Cargo.toml
pallets/registry/Cargo.toml
scripts/create-test-keyshares/Cargo.toml

Bumps Synedrion to a published version, allowing us to release our own workspace.
There are no functional changes from the pinned revision we were previously using.

Bump to Synedrion `v0.2.0-beta.0`

---

pallets/propagation/src/lib.rs
pallets/propagation/src/tests.rs

Currently dkg request fires every block, now it only fires when it is needed

Only fire DKG off-chain worker request when needed

---

CHANGELOG.md
crates/threshold-signature-server/src/lib.rs
crates/threshold-signature-server/src/user/tests.rs
crates/threshold-signature-server/src/validator/tests.rs
crates/threshold-signature-server/tests/register_sign_reshare_sign.rs
node/cli/src/service.rs
pallets/propagation/src/lib.rs
pallets/propagation/src/tests.rs
pallets/staking/src/lib.rs

It looks our OCW was pending a POST request to a non-existent TSS endpoint when rotating
keyshares.
I believe the reason why this wasn't caught earlier is because all of our tests enter the
endpoint manually, and they all used the correct one. This is another point for
@ameba23's idea of using the OCW more in tests.
I tidied up a few things here, including the endpoint name. The `/validator` prefix seems
unnecessary to me and is consistent with the `/generate_parent_key` endpoint.

Use correct key rotation endpoint in OCW

---

RELEASE_CHECKLIST.md

The backslash, when treated literally, will cause the `entropy-test-cli` to fail to load its subcommand. In Markdown, this should either have been written as:
```
the command \
with a new line
```
or just remove the slash and leave the single-line code formatting. I propose this simpler, latter option.

Single line for release checklist command

---

CHANGELOG.md
Cargo.lock
crates/client/Cargo.toml
crates/kvdb/Cargo.toml
crates/protocol/Cargo.toml
crates/shared/Cargo.toml
crates/test-cli/Cargo.toml
crates/testing-utils/Cargo.toml
crates/threshold-signature-server/Cargo.toml
crates/threshold-signature-server/src/user/tests.rs
node/cli/Cargo.toml
pallets/attestation/Cargo.toml
pallets/oracle/Cargo.toml
pallets/parameters/Cargo.toml
pallets/programs/Cargo.toml
pallets/propagation/Cargo.toml
pallets/registry/Cargo.toml
pallets/slashing/Cargo.toml
pallets/staking/Cargo.toml
pallets/transaction-pause/Cargo.toml
runtime/Cargo.toml
scripts/create-test-keyshares/Cargo.toml

Updates versions and `CHANGELOG` for the full release of `v0.3.0`.
I made a couple small edits in order to use a released version of `tdx-quote` and to
address some build warnings on tests. No behaviour has changed though.
One other thing to note here is that since `master` has introduced some breaking changes
since the release, this PR is targeting a dedicated releases branch based off the `rc.1` tag.
Follow up to https://github.com/entropyxyz/entropy-core/pull/1098.

Release `v0.3.0`

---

CHANGELOG.md
Cargo.lock
crates/client/Cargo.toml
crates/kvdb/Cargo.toml
crates/protocol/Cargo.toml
crates/shared/Cargo.toml
crates/test-cli/Cargo.toml
crates/testing-utils/Cargo.toml
crates/threshold-signature-server/Cargo.toml
crates/threshold-signature-server/src/user/tests.rs
node/cli/Cargo.toml
pallets/attestation/Cargo.toml
pallets/oracle/Cargo.toml
pallets/parameters/Cargo.toml
pallets/programs/Cargo.toml
pallets/propagation/Cargo.toml
pallets/registry/Cargo.toml
pallets/slashing/Cargo.toml
pallets/staking/Cargo.toml
pallets/transaction-pause/Cargo.toml
runtime/Cargo.toml
scripts/create-test-keyshares/Cargo.toml

In https://github.com/entropyxyz/entropy-core/pull/1129 I made a new base branch for the release called `release/v0.3.0`. This caused a problem since that's the naming convention we used for _tags_, creating an ambiguous situation for Git. What I should've done was named the branch `release-v0.3.0` (note the dash instead of the backslash).
While I could push forward and have a tag and branch with the same name I figured it would be better to address this by making a new PR targeting a non-conflicting base branch. I'm gonna have to delete the base branch for #1129 eventually, so note that the diff there might look a little wonky.
There are **no code differences** between this and #1129.

Release `v0.3.0` against new branch

---

crates/protocol/src/errors.rs
crates/protocol/src/execute_protocol.rs
crates/protocol/tests/protocol.rs

Related issue: https://github.com/entropyxyz/entropy-core/issues/641
Now that some fixes in synedrion mean that `Session` is `sync`, and we only need read access to `Session` to process / create messages, message processing / creation from different peers during a round should be able to happen concurrently without needing a mutex. Things are a bit more complicated than last time i tried to do this because we have to handle messages from future sub-protocol for the DKG flow (which is now composed of 3 sub-protocols).
This PR adds concurrency both for processing incoming messages (calls to `session.process_message`) and outgoing messages (calls to `session.make_message`).
Since most of the time goes into processing incoming messages (according to my benchmarks from a while back), i was …

Concurrently process messages in protocol execution loop

---

Cargo.lock
crates/protocol/src/lib.rs
crates/test-cli/Cargo.toml
crates/test-cli/src/lib.rs
crates/test-cli/src/main.rs

Closes https://github.com/entropyxyz/entropy-core/issues/1163
This adds optional JSON output to the test CLI.
This is activated with the `--json` or `-j` command line argument.  Note that it must be given before the subcommand like this: `entropy-test-cli --json status` and not `entropy-test-cli status --json`.
Currently not all available information is given, for example the status command gives you the hashes of stored programs and account ids of registered accounts, but not the additional metadata you will see in the non-json output, such as which programs are associated with which account, who stored a program, how many times a program was used, etc.  These fields could easily be added so please say if they would be useful. 
Generally binary data is represented as hex.
```
$ …
```

Add json output to test CLI command output

---

CHANGELOG.md
Cargo.lock
crates/client/src/client.rs
crates/client/src/errors.rs
crates/client/src/tests.rs
crates/client/src/user.rs
crates/test-cli/Cargo.toml
crates/test-cli/src/lib.rs
crates/threshold-signature-server/src/attestation/api.rs
crates/threshold-signature-server/src/attestation/errors.rs
crates/threshold-signature-server/src/attestation/tests.rs
crates/threshold-signature-server/src/lib.rs

Part of https://github.com/entropyxyz/entropy-core/issues/982 - see https://github.com/entropyxyz/entropy-core/issues/982#issuecomment-2456757856
This adds an endpoint to the TSS server which allows the operator to get a quote for use in the `validate`, `change_endpoint`, and `change_tss_accounts` extrinsics.
In doing this i noticed a possible problem with our design.  I have made an issue: https://github.com/entropyxyz/entropy-core/issues/1174

Add TSS endpoint to get TDX quote

---

pallets/staking/src/lib.rs
pallets/staking/src/tests.rs

Adds a guard for no current signer which will also act as a not jumpstarted guard as jumpstarting sets signers. Doing it this way saves a look up and is a little more protective IMO

Add no current signer guard

---

crates/test-cli/src/lib.rs

Closes https://github.com/entropyxyz/entropy-core/issues/1085

Test CLI - if no configuration / aux info interfaces files are provided, default to an empty vector

---

CHANGELOG.md
crates/client/src/tests.rs
crates/shared/src/types.rs
crates/threshold-signature-server/src/attestation/api.rs
crates/threshold-signature-server/src/attestation/errors.rs
crates/threshold-signature-server/src/attestation/tests.rs
pallets/attestation/src/lib.rs
pallets/attestation/src/tests.rs
pallets/staking/src/benchmarking.rs
pallets/staking/src/lib.rs
pallets/staking/src/mock.rs

Closes https://github.com/entropyxyz/entropy-core/issues/1174
This removes block number from the quote input data as this is time sensitive and it can be difficult to know at the moment of creating the quote when it will be validated.
Instead we use a `QuoteContext` enum which indicates the context in which this quote is intended to be used.
This can currently be one of:
- The `validate` extrinsic
- The `change_endpoint` extrinsic
- The `change_threshold_accounts` extrinsic

Use context, not block number in TDX quote input data

---

CHANGELOG.md
crates/threshold-signature-server/src/validator/api.rs
crates/threshold-signature-server/src/validator/tests.rs
crates/threshold-signature-server/tests/register_sign_reshare_sign.rs
node/cli/src/service.rs

When fixing the reshare test in https://github.com/entropyxyz/entropy-core/pull/1162 i found two problems which mean the resharing will not work in production.
1. The lookup key for the rotate keyshares endpoint is incorrect
2. The http client used by the propagation pallet has a timeout set to two seconds.  When this timeout is met, the http client closes the connection, causing axum to kill the task handling the request. This causes the reshare to stop mid-protocol.  This is fixed here by running the protocol in a spawned task, as we do with DKG.
I have fixed these in https://github.com/entropyxyz/entropy-core/pull/1162 - but since that PR makes quite some changes to our test setup, and still needs some cleaning up, i wanted to put the fixes in a separate PR, so its clear what they are, …

Reshare in a spawned task and fix propagation pallet rotate keyshares endpoint lookup key

---

crates/threshold-signature-server/src/attestation/api.rs
crates/threshold-signature-server/src/attestation/errors.rs

In `entropy-tss`, real (non-mock) TDX quotes are currently only generated when the `production` feature flag is enabled.
Unfortunately that means the code behind that flag is not tested in CI.  I recently set up a test network on TDX hardware to test attestation, and `entropy-tss` would not compile with the `production` feature flag enabled due to the error type which `config-tsm::generate_quote` having changed. This PR fixes that.
I have also made an issue to have the error type improved before the next release of `configfs-tsm`: https://github.com/entropyxyz/configfs-tsm/issues/7
We could also consider adding `cargo check -p entropy-tss --feature production` to our CI.

Fix error handling for TDX quote generation in production

---

crates/client/src/user.rs

When building `entropy-client` for the status page i get the following error:
```
Compiling entropy-client v0.3.0 (https://github.com/entropyxyz/entropy-core.git#425b2819)
error[E0277]: `sp_core::sr25519::Public` doesn't implement `std::fmt::Display`
--> /home/turnip/.cargo/git/checkouts/entropy-core-6e6c2c3deec0f284/425b281/crates/client/src/user.rs:163:57
|
163 |     tracing::debug!("{} is requesting an attestation.", attestee.public());
|                                                         ^^^^^^^^^^^^^^^^^ `sp_core::sr25519::Public` cannot be formatted with the default formatter
|
= help: the trait `std::fmt::Display` is not implemented for `sp_core::sr25519::Public`
= note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
= note: this error …
```

Use debug when displaying public key for attestation client function

---

crates/testing-utils/Cargo.toml
crates/threshold-signature-server/Cargo.toml

I am sometimes seeing the error:
```
error: failed to select a version for the requirement `parity-scale-codec = "^3.7.0"`
candidate versions found which didn't match: 3.6.12, 3.6.11, 3.6.10, ...
location searched: crates.io index
required by package `entropy-testing-utils v0.3.0 (https://github.com/entropyxyz/entropy-core.git#d192cdc0)`
... which satisfies git dependency `entropy-testing-utils` of package `entropy-chain-nodes-test v0.1.0 (/home/turnip/radish/src/entropy/entropy-chain-nodes-test)`
if you are looking for the prerelease package it needs to be specified explicitly
parity-scale-codec = { version = "3.6.8-alpha.1" }
```
This is because `parity-scale-codec` 3.7.0 has been yanked. This PR downgrades it to the latest stable version.

Downgrade parity-scale-codec as version we currently use has been yanked

---

CHANGELOG.md
node/cli/src/chain_spec/dev.rs
node/cli/src/chain_spec/mod.rs
node/cli/src/chain_spec/tdx_testnet.rs
node/cli/src/command.rs

This add a chainspec type for the setup i am currently using for a simple test network with the TSS servers running in TDX virtual machines.
It is just the development chainspec with a custom TSS endpoint (we need TSS nodes to have their public IP address), custom PCK certificates (we can't use the mock ones), and a custom accepted MRTD value from the entropy-tss VM image i am currently using.
I don't want to hardcode the IP address as i think it will probably change (hopefully we find something cheaper!), so it is read from an environment variable.
Currently the PCK is hard-coded.  Ideally i would like to read it in from a certificate file, using the same code that the staking extension pallet uses to extract and verify PCKs from certificates. But this would mean having the staking …

Add TDX test network chainspec

---

CHANGELOG.md
crates/shared/src/types.rs

@HCastano made some additional suggestions to https://github.com/entropyxyz/entropy-core/pull/1209 that i didnt see until after i hit merge.
This is a tiny PR with no functional code changes (rm comment and changelog entry).

Minor edits missed from review of #1209

---

crates/threshold-signature-server/src/helpers/launch.rs
crates/threshold-signature-server/src/user/errors.rs
crates/threshold-signature-server/src/validator/api.rs
crates/threshold-signature-server/src/validator/errors.rs
crates/threshold-signature-server/src/validator/tests.rs

The forbidden key check function is only called in tests and can be removed since we no longer have http routes which allow reading data from the kvdb.
Closes https://github.com/entropyxyz/entropy-core/issues/1221

Remove forbidden key check

---

Cargo.lock
crates/client/Cargo.toml
crates/testing-utils/Cargo.toml
crates/threshold-signature-server/Cargo.toml
pallets/attestation/Cargo.toml
pallets/staking/Cargo.toml

`tdx-quote` is now published as 0.0.3.  This PR uses that rather than the git version.

Use tdx-quote v0.0.3 - not git version

---

CHANGELOG.md
crates/threshold-signature-server/src/helpers/user.rs
crates/threshold-signature-server/src/user/api.rs
crates/threshold-signature-server/src/user/errors.rs
crates/threshold-signature-server/src/user/tests.rs

Add a way for programs to have different versions
Can be made more efficient by caching runtime version and using cached instead of spinning up a new one (#1251)

Allow different versions for programs

---

scripts/check-entropy-shared.sh

This is a small PR which adds a script which runs `cargo check` on `entropy-shared` with all the different combinations of feature flags / targets which will be used. 
This is useful to check that changes to entropy-shared have not broken anything, without needing to run the entire CI pipeline.
I found this useful recently when getting into a big muddle after making some changes there, so i would like to keep this script in the scripts directory for next time.

Add entropy-shared check script

---

crates/kvdb/src/kv_manager/kv.rs

Relates to https://github.com/entropyxyz/entropy-core/issues/1260
This makes it so that errors from the key-value store command handler are sent through the response channel so they can be propagated to the caller of the public methods.
Without this, whichever database error occurs, the caller will always see `Recv Error: channel closed`.

Propagate key-value db command handler errors

---

CHANGELOG.md
crates/shared/src/types.rs
crates/threshold-signature-server/src/helpers/user.rs
crates/threshold-signature-server/src/node_info/tests.rs
crates/threshold-signature-server/src/user/errors.rs
crates/threshold-signature-server/src/user/tests.rs
deny.toml

Adds a no hash option. After talking with @rh0delta a possibility to send a hash to be signed is a good use case, can do this hackily with custom hash, but this should be an out of the box option

Add no hash option

---

crates/threshold-signature-server/src/user/tests.rs
crates/threshold-signature-server/src/validator/tests.rs
crates/threshold-signature-server/tests/sign_eth_tx.rs

There have been two tests which have been randomly failing for the last month or two
(see #1119 and #1273).
This has caused problems with other CI jobs which would've otherwise passed but now fail
because of one of these two tests. I hate to ignore tests, but until they can run more
reliably we shouldn't have them running as part of the CI.
@JesseAbram can you take some time in the next couple of days to get these sorted out 🙏

Ignore failing jumpstart and reshare tests

---

crates/threshold-signature-server/tests/jumpstart_register_sign.rs

This is a follow up to #1274 - looks like there are more failing tests
than I originally thought.

Ignore another failing integration test

---

Cargo.lock
crates/client/Cargo.toml
crates/test-cli/Cargo.toml
crates/testing-utils/Cargo.toml
crates/threshold-signature-server/Cargo.toml

Reverts entropyxyz/entropy-core#1286 which was automatically merged despite breaking CI.
This is a short term proposal to get CI to pass on master again for now.
Long term i think we should be able to re-open that PR and fix the issue with having duplicate indexes.

Revert "Bump parity-scale-codec from 3.7.2 to 3.7.4 in the patch-dependencies group"

---

crates/protocol/src/execute_protocol.rs

This was suggested by @fjarri here:
https://github.com/entropyxyz/manul/pull/91#issuecomment-2639203564
Since synedrion's message processing methods are synchronous and computationally heavy, it does not make sense to run them in async tokio tasks as this may prevent the executor from moving other tasks forward.
This PR uses [`tokio::task::spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html) to run them as blocking, syncronous tasks instead.
Unfortunately this does not appear to give any improvement in performance when testing signing with 8 parties.
Since we will be soon swapping this out for the protocol execution loop provided by manul, it probably makes no difference whether or not we merge this.  But gonna put it up anyway.

Use `spawn_blocking` when processing synedrion messages

---

Cargo.lock

I made a mistake when resolving conflicts in order to merge https://github.com/entropyxyz/entropy-core/pull/1294
(needed for CI to pass)
And ended up with the change still being present in the lockfile.  This puts it back.

Revert lockfile following merging #1294

---

Cargo.lock
crates/client/Cargo.toml
crates/protocol/Cargo.toml
crates/test-cli/Cargo.toml
crates/testing-utils/Cargo.toml
crates/threshold-signature-server/Cargo.toml
node/cli/Cargo.toml
pallets/staking/Cargo.toml

Reverts entropyxyz/entropy-core#1308 
This is starting to drive me insane.  If we don't find a solution to https://github.com/entropyxyz/entropy-core/issues/1302 soon, i propose we remove https://github.com/entropyxyz/entropy-core/blob/eaa13f8c70bcd7e31112bdbe9ce8f5e64ad70b42/.github/workflows/dependabot-auto-merge.yml until we figure out how to put in a clause that CI must pass.

Revert "Bump the patch-dependencies group with 6 updates"

---

Dockerfile

Closes: https://github.com/entropyxyz/entropy-core/issues/1324
These Dockerfile lint warnings keep popping up and make it hard to see the actual CI problems.

Style improvements to Dockerfile

---

crates/testing-utils/src/node_proc.rs
crates/threshold-signature-server/src/user/api.rs
crates/threshold-signature-server/src/user/tests.rs

Very similar issue to #1331 logs support that
```
2025-03-07 16:44:26 💤 Idle (3 peers), best: #8 (0xa2ba…e4f2), finalized #6 (0x5b43…2649), ⬇ 3.2kiB/s ⬆ 3.3kiB/s    
2025-03-07 16:44:28 💤 Idle (3 peers), best: #8 (0xa2ba…e4f2), finalized #6 (0x5b43…2649), ⬇ 3.1kiB/s ⬆ 2.9kiB/s    
2025-03-07 16:44:29 💤 Idle (3 peers), best: #8 (0xa2ba…e4f2), finalized #6 (0x5b43…2649), ⬇ 3.3kiB/s ⬆ 3.5kiB/s    
2025-03-07 16:44:30 🙌 Starting consensus session on top of parent 0xa2ba17533aea7f7348f5f006324c06e49a5acf3bbc89aec8c452743eb626e4f2    
2025-03-07 16:44:30 🎁 Prepared block for proposing at 9 (1 ms) [hash: 0xcda6715ca3ac23f70b9bb6f413c3e50a69338a71037fcf51fd192be9c36b2808; parent_hash: 0xa2ba…e4f2; extrinsics (2): [0x5cf4…bf52, 0x3f2f…1b5d]    
2025-03-07 16:44:30 🔖 Pre-sealed block for proposal …
```

Validate jumpstart mutex handling

---

crates/threshold-signature-server/src/node_info/api.rs

This is a small fix needed to compile `entropy-tss` in with the `production` feature enabled.
Ideally problems like this should be picked up in CI - we should probably be running `cargo check --features=production`.

Fix enum variant name for production build details

---

.github/workflows/container-build-and-push.yaml
CHANGELOG.md
Dockerfile
RELEASE_CHECKLIST.md

This makes it possible to build entropy with the `production` feature flag in the release pipeline if the release tag contains the string 'production'.
An alternative would be to make production mode default and 'mock' need to be specified.  But i think this is fine for now.

Release in production mode unless 'non-TDX' is specified in release tag

---

CHANGELOG.md
crates/threshold-signature-server/src/attestation/api.rs
crates/threshold-signature-server/src/attestation/errors.rs
crates/threshold-signature-server/src/node_info/api.rs
crates/threshold-signature-server/src/node_info/errors.rs
crates/threshold-signature-server/src/node_info/tests.rs

Closes https://github.com/entropyxyz/entropy-core/issues/1354
Example output of `/info` on this branch:
```json
{"ready":false,"tss_account":"5Dy7r8pTEoJJDGRrebQvFyWWfKCpTJiXxz7NxbKeh8zXE7Vk","x25519_public_key":[40,170,149,217,225,231,193,134,157,146,161,94,118,146,134,201,179,206,106,186,35,6,93,138,104,203,205,68,208,90,255,7],"provisioning_certification_key":[2,35,153,56,144,219,98,192,9,186,39,114,167,154,75,24,93,39,159,234,180,105,135,89,110,203,179,93,192,164,177,214,78]}
```

Include Provisioning Certification Key (PCK) in the entropy-tss `/info` HTTP route output

---

CHANGELOG.md
crates/kvdb/src/kv_manager/tests.rs
crates/kvdb/src/lib.rs
crates/threshold-signature-server/src/helpers/launch.rs
crates/threshold-signature-server/src/helpers/tests.rs

This relates to this issue: https://github.com/entropyxyz/entropy-core/issues/1197
This changes the directory where `entropy-tss` stores its key-value store but only for TDX production builds.  The base directory for these builds is now `/persist` rather than the working directory where the binary is run.
This pairs with https://github.com/entropyxyz/meta-entropy-tss/pull/5 which mounts a persistent filesystem to the path `/persist` (the rest of the filesystem is in-memory only).
Rather than fix this issue complete by setting the storage directory to something conventional, i am trying to minimize the amount of breaking changes to our current setup since we are talking about doing another non-TDX deployment soon.

Change `entropy-tss` storage location for TDX production builds

---

crates/threshold-signature-server/src/backup_provider/api.rs
crates/threshold-signature-server/src/backup_provider/errors.rs
crates/threshold-signature-server/src/helpers/launch.rs

Closes https://github.com/entropyxyz/entropy-core/issues/1379
When requesting both the nonce and the encryption key, we use the `backoff` crate to repeatedly send requests to the backup provider (another TSS node) for 15 mins. This is for the event that they themselves are still getting setup.
On failure, we copy the current db directory to `<directory name>-backup-<timestamp>` and start fresh.

Repeatedly attempt to retrieve TSS db backup and on failure start fresh 

---

RELEASE_CHECKLIST.md

This is a small fix to the commands giving in the release checklist for testing the network with docker-compose.
Without this small change i get:
```
Error: A mnemonic must be given either by the command line option or DEPLOYER_MNEMONIC environment variable
```
when using the given CLI command to jumpstart the network.

Tiny fix to command in release checklist

---

crates/threshold-signature-server/src/lib.rs
node/cli/src/chain_spec/dev.rs
node/cli/src/chain_spec/integration_tests.rs
node/cli/src/chain_spec/testnet.rs
node/cli/src/service.rs

https://github.com/entropyxyz/entropy-core/pull/1385 is failing CI because of new clippy rules.  I decided to put the fixes in a separate PR to avoid cluttering up the diff with unrelated stuff.

Fixes for latest clippy rules

---

.github/workflows/build-and-run-node-test.yaml

In some cases tests were not being run despite code having been changed, due to an issue with the check as to whether code changes. Eg: https://github.com/entropyxyz/entropy-core/actions/runs/14751508488/job/41409844605?pr=1392
@cooldracula suggested this fix - making it so that all commit history is checked out, so `git diff` can find the commits we are referring to.

Fix CI check for code changed (suggested by Zach)

---

.github/workflows/build-and-run-node-test.yaml
crates/testing-utils/src/substrate_context.rs
crates/threshold-signature-server/src/signing_client/tests.rs

@ameba23 Found a race condition in this test here https://github.com/entropyxyz/entropy-core/actions/runs/14791179943/job/41528489582
The issue is the ```.staking_extension().proactive_refresh()``` gets cleared at the end of each block. It gets set at block 0 with default so it has a result. Then when it gets cleared it causes an error. This is good behaviour normally, as this only will get fired once by the chain, but bad for this test
I set it to a chain that won't produce blocks so the test doesn't have to race to make this call

FIx test_node_process_stationary_local

---

crates/client/src/user.rs
crates/protocol/src/execute_protocol.rs
crates/threshold-signature-server/src/backup_provider/api.rs
crates/threshold-signature-server/src/helpers/launch.rs
crates/threshold-signature-server/src/user/api.rs

Closes #1271 
@ameba23 is this enough you think or should I go through the whole code base and do this?

Use ss58 for loggings

---

crates/protocol/Cargo.toml
crates/protocol/js-README.md

`entropy-protcol` currently will not compile for wasm. This PR fixes it.
Example of this failing: https://github.com/entropyxyz/entropy-core/actions/runs/14794865619/job/41539621619?pr=1414

Fix `entropy-protocol` compilation on wasm

---

.github/actions/install-dependencies/action.yaml
.github/workflows/build-and-run-node-test.yaml
.github/workflows/lint-and-check-licenses.yaml
crates/kvdb/src/encrypted_sled/tests.rs
crates/threshold-signature-server/src/backup_provider/api.rs
crates/threshold-signature-server/src/backup_provider/errors.rs
crates/threshold-signature-server/src/backup_provider/tests.rs
crates/threshold-signature-server/src/lib.rs
node/cli/src/chain_spec/dev.rs
node/cli/src/chain_spec/integration_tests.rs
node/cli/src/chain_spec/testnet.rs
node/cli/src/service.rs
rust-toolchain.toml

This cherry-picks commit `1634692c`, adding the fix from PR https://github.com/entropyxyz/entropy-core/pull/1385 to release v0.4.0-rc1
I tried releasing directly from that commit and had issues, even though the changed in-between are mostly just minor version bumps from dependabot - but to be sure i want to check CI passes here before releasing on this branch.
To get CI to run i also needed this: https://github.com/entropyxyz/entropy-core/pull/1410 so i cherry picked that as well.

Fix for release v0.4.0

---

.github/actions/install-dependencies/action.yaml
.github/workflows/lint-and-check-licenses.yaml
CHANGELOG.md
crates/threshold-signature-server/src/lib.rs
runtime/Cargo.toml
rust-toolchain.toml

See https://github.com/entropyxyz/entropy-core/issues/1435

Downgrade rust version to 1.86 as a temporary measure until we upgrade sp-io

---

crates/shared/src/attestation.rs

Probably we also need this fix on master, but here i am just putting it for the v0.4.0 version to get the status page working.
This was needed in https://github.com/entropyxyz/entropy-network-status-page/pull/27

Fixes for entropy-client on wasm for release v0.4.0

---

pallets/staking/src/tests.rs

This test is failing with the new update (weird it wasn't picked up in the CI, anyways instead of dealing with locks we check free balance now

Fix staking it_deletes_when_no_bond_left test

---

crates/testing-utils/src/node_proc.rs
crates/testing-utils/src/substrate_context.rs
crates/threshold-signature-server/src/user/tests.rs

Idk why but my nodes were not able to find themselves, not sure how it happened and why not on CI, however now I create alice's node key deterministically so it is hardcoded in our tests and nodes can find each other, this fixes the issue and in general makes this more stable

Deterministic alice bootnode for testing

---

node/cli/Cargo.toml
node/cli/build.rs
node/cli/src/chain_spec/testnet.rs
node/cli/src/endowed_accounts.rs

This is identical to https://github.com/entropyxyz/entropy-core/pull/1466 but targets master rather than the v.0.4.0 release branch.
Since this works with our current deployment, i would like to have it in the next release to minimize changes.

Add endowed accounts - at compile time (cherry pick of #1466)

---

pallets/staking/src/benchmarking.rs

Threshold would pass in test but fail in running benchmark, this is because instead of control we have in test to set it to null, the quote would be randomly generate, this is mitigated by manually insterting the quote instead of assuming it is null

Fix change_threshold benchmark

---

docker-compose.yaml

Closes #1513
See also https://github.com/entropyxyz/devops-infrastructure/issues/121
On this branch i am now able to have all 4 chain nodes run successfully with the docker-compose local devnet.  But i am not sure if there are some cases where it would cause a problem that the chain nodes cannot be re-started without generating a new node key (which i think is the libp2p id used in discovery).
But i propose to merge this for now, as without it the docker-compose setup does not work at all (for me at least).
@entropyxyz/system-reliability-engineers

Force node key generation in docker-compose local devnet

---

crates/threshold-signature-server/Cargo.toml

Otherwise entropy-tss fails to compile in production mode, see https://github.com/entropyxyz/entropy-core/actions/runs/16616462687/job/47010141118
Relates to https://github.com/entropyxyz/entropy-core/issues/1502 and https://github.com/entropyxyz/entropy-core/pull/1505

When entropy-tss is built in production mode, entropy-client should be built in production mode
